### ISSUE TITLE
`Duplicate ID Error` occurs before a component has completely unmounted

### ISSUE THREAD

**Issue by mggower** [sayari-analytics/strictly-formed#8]
`Duplicate Id Error` occurs because of a race condition between components that share an `Id`. This is common when a more universal component (like a toggle) is used in more than one view. Once the first component has unmounted, the `Id` has not been removed from the cache before the second component has mounted and logs the duplicate `Id` error. The op should be considered safe and not log any errors.

**Comment by JulietAdams** [comment]
closing this and going to open a different ticket to just remove strictly-formed (which will resolve these errors)
